INFO 2025-07-06 22:56:39,669 autoreload 11208 3144 Watching for file changes with StatReloader
WARNING 2025-07-06 22:56:42,647 log 11208 12924 Not Found: /
WARNING 2025-07-06 22:56:42,647 basehttp 11208 12924 "GET / HTTP/1.1" 404 2311
WARNING 2025-07-06 22:56:42,754 log 11208 12924 Not Found: /favicon.ico
WARNING 2025-07-06 22:56:42,754 basehttp 11208 12924 "GET /favicon.ico HTTP/1.1" 404 2362
INFO 2025-07-06 22:56:44,995 basehttp 11208 12924 "GET /admin/ HTTP/1.1" 302 0
INFO 2025-07-06 22:56:45,076 basehttp 11208 12924 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4182
INFO 2025-07-06 22:56:45,086 basehttp 11208 12924 "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2025-07-06 22:56:45,086 basehttp 11208 25768 "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2025-07-06 22:56:45,086 basehttp 11208 21012 "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2025-07-06 22:56:45,102 basehttp 11208 25768 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2025-07-06 22:56:45,102 basehttp 11208 12924 "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2025-07-06 22:56:45,102 basehttp 11208 21012 "GET /static/admin/css/login.css HTTP/1.1" 304 0
INFO 2025-07-06 22:56:45,104 basehttp 11208 21012 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2025-07-06 22:57:14,586 autoreload 12784 13232 Watching for file changes with StatReloader
INFO 2025-07-06 22:57:18,313 basehttp 12784 13948 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4351
INFO 2025-07-06 22:57:22,178 basehttp 12784 13948 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4351
INFO 2025-07-06 22:57:26,612 basehttp 12784 13948 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2025-07-06 22:57:26,717 basehttp 12784 13948 "GET /admin/ HTTP/1.1" 200 8958
INFO 2025-07-06 22:57:26,741 basehttp 12784 13948 "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
INFO 2025-07-06 22:57:26,747 basehttp 12784 6352 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2025-07-06 22:57:26,748 basehttp 12784 13948 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
INFO 2025-07-06 22:57:29,335 basehttp 12784 13948 "GET /admin/gps_data/apilog/ HTTP/1.1" 200 11490
INFO 2025-07-06 22:57:29,359 basehttp 12784 13948 "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2025-07-06 22:57:29,360 basehttp 12784 26568 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2025-07-06 22:57:29,362 basehttp 12784 13948 "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2025-07-06 22:57:29,364 basehttp 12784 26424 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2025-07-06 22:57:29,364 basehttp 12784 26568 "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2025-07-06 22:57:29,365 basehttp 12784 16580 "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2025-07-06 22:57:29,365 basehttp 12784 13948 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2025-07-06 22:57:29,366 basehttp 12784 5096 "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2025-07-06 22:57:29,366 basehttp 12784 26424 "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2025-07-06 22:57:29,368 basehttp 12784 26424 "GET /static/admin/img/search.svg HTTP/1.1" 304 0
INFO 2025-07-06 22:57:29,370 basehttp 12784 26424 "GET /static/admin/js/filters.js HTTP/1.1" 304 0
INFO 2025-07-06 22:57:29,424 basehttp 12784 6352 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 22:57:29,443 basehttp 12784 6352 "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 304 0
INFO 2025-07-06 22:57:31,130 basehttp 12784 6352 "GET /admin/gps_data/devicestatus/ HTTP/1.1" 200 12517
INFO 2025-07-06 22:57:31,192 basehttp 12784 6352 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 22:57:31,199 basehttp 12784 6352 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
INFO 2025-07-06 22:57:31,836 basehttp 12784 6352 "GET /admin/gps_data/device/ HTTP/1.1" 200 11331
INFO 2025-07-06 22:57:31,902 basehttp 12784 6352 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 22:57:32,723 basehttp 12784 6352 "GET /admin/gps_data/gpsrecord/ HTTP/1.1" 200 12765
INFO 2025-07-06 22:57:32,792 basehttp 12784 6352 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 22:57:34,507 basehttp 12784 6352 "GET /admin/gps_data/gpsrecord/add/ HTTP/1.1" 200 40158
INFO 2025-07-06 22:57:34,530 basehttp 12784 5096 "GET /static/admin/css/forms.css HTTP/1.1" 304 0
INFO 2025-07-06 22:57:34,533 basehttp 12784 16580 "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
INFO 2025-07-06 22:57:34,533 basehttp 12784 5096 "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
INFO 2025-07-06 22:57:34,657 basehttp 12784 6352 "GET /static/admin/js/calendar.js HTTP/1.1" 200 9141
INFO 2025-07-06 22:57:34,666 basehttp 12784 26424 "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
INFO 2025-07-06 22:57:34,669 basehttp 12784 26424 "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
INFO 2025-07-06 22:57:34,675 basehttp 12784 13948 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 22:57:34,720 basehttp 12784 26424 "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
INFO 2025-07-06 22:57:34,721 basehttp 12784 13948 "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
INFO 2025-07-06 22:57:38,988 basehttp 12784 13948 "GET /admin/gps_data/device/ HTTP/1.1" 200 11331
INFO 2025-07-06 22:57:39,053 basehttp 12784 13948 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 22:57:40,146 basehttp 12784 13948 "GET /admin/gps_data/device/add/ HTTP/1.1" 200 12543
INFO 2025-07-06 22:57:40,225 basehttp 12784 13948 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 22:57:45,650 basehttp 12784 13948 "GET /admin/gps_data/devicestatus/ HTTP/1.1" 200 12517
INFO 2025-07-06 22:57:45,720 basehttp 12784 13948 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 22:57:47,254 basehttp 12784 13948 "GET /admin/gps_data/devicestatus/add/ HTTP/1.1" 200 15856
INFO 2025-07-06 22:57:47,318 basehttp 12784 13948 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 22:57:50,996 basehttp 12784 13948 "GET /admin/gps_data/apilog/ HTTP/1.1" 200 11490
INFO 2025-07-06 22:57:51,157 basehttp 12784 13948 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
WARNING 2025-07-06 22:59:22,921 log 12784 25156 Not Found: /health/
WARNING 2025-07-06 22:59:22,923 basehttp 12784 25156 "GET /health/ HTTP/1.1" 404 2350
INFO 2025-07-06 23:01:18,098 basehttp 12784 5940 "GET /api/health/ HTTP/1.1" 200 108
INFO 2025-07-06 23:01:20,163 basehttp 12784 5188 "POST /api/devices/ HTTP/1.1" 201 183
INFO 2025-07-06 23:01:22,259 views 12784 5392 GPS record stored for device 123456789012345
INFO 2025-07-06 23:01:22,260 basehttp 12784 5392 "POST /api/store/ HTTP/1.1" 201 66
INFO 2025-07-06 23:01:24,323 views 12784 20992 Received GPS data: 6 bytes
INFO 2025-07-06 23:01:24,374 basehttp 12784 20992 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:01:26,453 basehttp 12784 25168 "GET /api/devices/123456789012345/ HTTP/1.1" 200 183
INFO 2025-07-06 23:01:28,544 basehttp 12784 19016 "GET /api/devices/123456789012345/records/ HTTP/1.1" 200 4838
INFO 2025-07-06 23:01:30,634 basehttp 12784 8572 "GET /api/stats/ HTTP/1.1" 200 149
WARNING 2025-07-06 23:01:46,141 log 12784 13948 Not Found: /admin/tracking/dataprocessingstatus/
WARNING 2025-07-06 23:01:46,142 basehttp 12784 13948 "GET /admin/tracking/dataprocessingstatus/ HTTP/1.1" 404 6530
WARNING 2025-07-06 23:01:48,325 log 12784 13948 Not Found: /admin/tracking/dataprocessingstatus/
WARNING 2025-07-06 23:01:48,325 basehttp 12784 13948 "GET /admin/tracking/dataprocessingstatus/ HTTP/1.1" 404 6530
WARNING 2025-07-06 23:01:51,086 log 12784 13948 Not Found: /
WARNING 2025-07-06 23:01:51,087 basehttp 12784 13948 "GET / HTTP/1.1" 404 2311
INFO 2025-07-06 23:01:54,178 basehttp 12784 13948 "GET /admin/ HTTP/1.1" 200 8958
INFO 2025-07-06 23:01:56,326 basehttp 12784 13948 "GET /admin/gps_data/apilog/ HTTP/1.1" 200 14277
INFO 2025-07-06 23:01:56,491 basehttp 12784 13948 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:01:58,799 basehttp 12784 13948 "GET /admin/gps_data/apilog/1/change/ HTTP/1.1" 200 14302
INFO 2025-07-06 23:01:58,868 basehttp 12784 13948 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:02:04,295 basehttp 12784 13948 "GET /admin/gps_data/devicestatus/ HTTP/1.1" 200 15086
INFO 2025-07-06 23:02:04,324 basehttp 12784 26424 "GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
INFO 2025-07-06 23:02:04,357 basehttp 12784 13948 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:02:07,288 basehttp 12784 13948 "GET /admin/gps_data/devicestatus/1/change/ HTTP/1.1" 200 16200
INFO 2025-07-06 23:02:07,456 basehttp 12784 13948 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:02:09,358 basehttp 12784 13948 "GET /admin/gps_data/device/ HTTP/1.1" 200 13736
INFO 2025-07-06 23:02:09,386 basehttp 12784 26424 "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
INFO 2025-07-06 23:02:09,419 basehttp 12784 13948 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:02:10,800 basehttp 12784 13948 "GET /admin/gps_data/device/1/change/ HTTP/1.1" 200 12899
INFO 2025-07-06 23:02:10,859 basehttp 12784 13948 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
ERROR 2025-07-06 23:02:12,470 log 12784 13948 Internal Server Error: /admin/gps_data/gpsrecord/
Traceback (most recent call last):
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\options.py", line 683, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'coordinates'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\utils.py", line 290, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\utils.py", line 330, in _get_non_gfk_field
    field = opts.get_field(name)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\options.py", line 685, in get_field
    raise FieldDoesNotExist(
        "%s has no field named '%s'" % (self.object_name, field_name)
    )
django.core.exceptions.FieldDoesNotExist: GPSRecord has no field named 'coordinates'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\library.py", line 359, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 354, in result_list
    "results": list(results(cl)),
               ~~~~^^^^^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 330, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 321, in __init__
    super().__init__(*items)
    ~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 219, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\utils.py", line 299, in lookup_field
    value = attr(obj)
  File "D:\GitHub\teltonika\django\gps_data\admin.py", line 91, in coordinates
    return format_html(
        '<a href="{}" target="_blank">{:.6f}, {:.6f}</a>',
        maps_url, obj.latitude, obj.longitude
    )
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\html.py", line 145, in format_html
    return mark_safe(format_string.format(*args_safe, **kwargs_safe))
                     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unknown format code 'f' for object of type 'SafeString'
ERROR 2025-07-06 23:02:12,489 basehttp 12784 13948 "GET /admin/gps_data/gpsrecord/ HTTP/1.1" 500 357925
INFO 2025-07-06 23:03:44,656 basehttp 12784 9672 "GET /api/health/ HTTP/1.1" 200 108
WARNING 2025-07-06 23:03:46,741 log 12784 26556 Bad Request: /api/devices/
WARNING 2025-07-06 23:03:46,741 basehttp 12784 26556 "POST /api/devices/ HTTP/1.1" 400 50
INFO 2025-07-06 23:03:48,857 views 12784 4696 GPS record stored for device 123456789012345
INFO 2025-07-06 23:03:48,858 basehttp 12784 4696 "POST /api/store/ HTTP/1.1" 201 66
INFO 2025-07-06 23:03:50,910 views 12784 14080 Received GPS data: 6 bytes
INFO 2025-07-06 23:03:51,074 basehttp 12784 14080 "POST /api/gps/ HTTP/1.1" 200 99
INFO 2025-07-06 23:03:53,151 basehttp 12784 20936 "GET /api/devices/123456789012345/ HTTP/1.1" 200 183
INFO 2025-07-06 23:03:55,240 basehttp 12784 11168 "GET /api/devices/123456789012345/records/ HTTP/1.1" 200 9631
INFO 2025-07-06 23:03:57,330 basehttp 12784 9500 "GET /api/stats/ HTTP/1.1" 200 151
WARNING 2025-07-06 23:04:32,041 log 12784 21548 Not Found: /health/
WARNING 2025-07-06 23:04:32,041 basehttp 12784 21548 "GET /health/ HTTP/1.1" 404 2350
WARNING 2025-07-06 23:04:32,045 log 12784 21548 Not Found: /health/
WARNING 2025-07-06 23:04:32,045 basehttp 12784 21548 "GET /health/ HTTP/1.1" 404 2350
INFO 2025-07-06 23:04:38,193 basehttp 12784 7120 "GET /api/health/ HTTP/1.1" 200 108
INFO 2025-07-06 23:04:42,511 basehttp 12784 7120 "GET /api/stats/ HTTP/1.1" 200 151
INFO 2025-07-06 23:07:56,767 autoreload 12784 13232 D:\GitHub\teltonika\django\gps_data\admin.py changed, reloading.
INFO 2025-07-06 23:07:57,147 autoreload 9136 18012 Watching for file changes with StatReloader
INFO 2025-07-06 23:09:01,459 basehttp 9136 10688 "GET /api/health/ HTTP/1.1" 200 108
INFO 2025-07-06 23:09:01,521 basehttp 9136 8536 "POST /api/devices/ HTTP/1.1" 201 200
WARNING 2025-07-06 23:09:01,579 log 9136 26472 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:01,580 basehttp 9136 26472 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:01,686 log 9136 10928 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:01,687 basehttp 9136 10928 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:01,810 log 9136 3892 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:01,810 basehttp 9136 3892 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:01,917 log 9136 22844 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:01,918 basehttp 9136 22844 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:02,043 log 9136 25620 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:02,044 basehttp 9136 25620 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:02,168 log 9136 14364 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:02,169 basehttp 9136 14364 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:02,292 log 9136 5096 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:02,292 basehttp 9136 5096 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:02,418 log 9136 25760 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:02,419 basehttp 9136 25760 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:02,544 log 9136 14068 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:02,545 basehttp 9136 14068 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:02,651 log 9136 18708 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:02,651 basehttp 9136 18708 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:02,777 log 9136 23304 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:02,778 basehttp 9136 23304 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:02,903 log 9136 14936 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:02,904 basehttp 9136 14936 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:03,029 log 9136 26220 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:03,029 basehttp 9136 26220 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:03,155 log 9136 17484 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:03,155 basehttp 9136 17484 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:03,280 log 9136 21580 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:03,281 basehttp 9136 21580 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:03,404 log 9136 21548 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:03,404 basehttp 9136 21548 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:03,512 log 9136 14000 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:03,512 basehttp 9136 14000 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:03,619 log 9136 3952 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:03,620 basehttp 9136 3952 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:03,726 log 9136 10408 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:03,726 basehttp 9136 10408 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:03,843 log 9136 21348 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:03,844 basehttp 9136 21348 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:03,967 log 9136 23516 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:03,967 basehttp 9136 23516 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:04,073 log 9136 9460 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:04,073 basehttp 9136 9460 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:04,181 log 9136 17940 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:04,181 basehttp 9136 17940 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:04,309 log 9136 12624 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:04,309 basehttp 9136 12624 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:04,432 log 9136 8836 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:04,433 basehttp 9136 8836 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:04,558 log 9136 4844 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:04,559 basehttp 9136 4844 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:04,685 log 9136 20472 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:04,686 basehttp 9136 20472 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:04,810 log 9136 4948 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:04,811 basehttp 9136 4948 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:04,916 log 9136 10244 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:04,916 basehttp 9136 10244 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:05,025 log 9136 19248 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:05,025 basehttp 9136 19248 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:05,131 log 9136 5896 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:05,132 basehttp 9136 5896 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:05,239 log 9136 16876 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:05,240 basehttp 9136 16876 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:05,348 log 9136 4256 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:05,349 basehttp 9136 4256 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:05,456 log 9136 8432 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:05,456 basehttp 9136 8432 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:05,563 log 9136 12728 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:05,563 basehttp 9136 12728 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:05,670 log 9136 5732 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:05,670 basehttp 9136 5732 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:05,789 log 9136 20936 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:05,789 basehttp 9136 20936 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:05,897 log 9136 11192 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:05,897 basehttp 9136 11192 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:06,004 log 9136 4944 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:06,004 basehttp 9136 4944 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:06,111 log 9136 3220 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:06,111 basehttp 9136 3220 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:06,217 log 9136 4608 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:06,218 basehttp 9136 4608 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:06,335 log 9136 26208 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:06,336 basehttp 9136 26208 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:06,461 log 9136 20704 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:06,461 basehttp 9136 20704 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:06,585 log 9136 26256 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:06,585 basehttp 9136 26256 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:06,690 log 9136 14756 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:06,690 basehttp 9136 14756 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:06,820 log 9136 23208 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:06,820 basehttp 9136 23208 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:06,925 log 9136 4264 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:06,926 basehttp 9136 4264 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:07,054 log 9136 19252 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:07,055 basehttp 9136 19252 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:07,161 log 9136 9296 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:07,161 basehttp 9136 9296 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:07,265 log 9136 10600 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:09:07,265 basehttp 9136 10600 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:09:07,381 log 9136 8900 Not Found: /api/devices/999888777666555/gps-records/
WARNING 2025-07-06 23:09:07,382 basehttp 9136 8900 "GET /api/devices/999888777666555/gps-records/?limit=10 HTTP/1.1" 404 5062
WARNING 2025-07-06 23:09:07,399 log 9136 11916 Not Found: /api/devices/999888777666555/gps-records/
WARNING 2025-07-06 23:09:07,399 basehttp 9136 11916 "GET /api/devices/999888777666555/gps-records/ HTTP/1.1" 404 5053
WARNING 2025-07-06 23:09:07,414 log 9136 9196 Not Found: /api/latest-gps-records/
WARNING 2025-07-06 23:09:07,415 basehttp 9136 9196 "GET /api/latest-gps-records/?limit=100 HTTP/1.1" 404 5012
WARNING 2025-07-06 23:09:07,429 log 9136 13344 Not Found: /api/devices/999888777666555/gps-records/
WARNING 2025-07-06 23:09:07,429 basehttp 9136 13344 "GET /api/devices/999888777666555/gps-records/?limit=50 HTTP/1.1" 404 5062
INFO 2025-07-06 23:10:07,747 basehttp 9136 5096 "GET /api/health/ HTTP/1.1" 200 108
WARNING 2025-07-06 23:10:07,779 log 9136 8432 Bad Request: /api/devices/
WARNING 2025-07-06 23:10:07,779 basehttp 9136 8432 "POST /api/devices/ HTTP/1.1" 400 50
WARNING 2025-07-06 23:10:07,852 log 9136 22824 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:07,852 basehttp 9136 22824 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:07,959 log 9136 5732 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:07,960 basehttp 9136 5732 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:08,087 log 9136 26464 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:08,087 basehttp 9136 26464 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:08,193 log 9136 8244 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:08,193 basehttp 9136 8244 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:08,319 log 9136 25344 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:08,319 basehttp 9136 25344 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:08,443 log 9136 11384 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:08,443 basehttp 9136 11384 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:08,548 log 9136 14364 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:08,548 basehttp 9136 14364 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:08,655 log 9136 12904 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:08,655 basehttp 9136 12904 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:08,770 log 9136 9460 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:08,770 basehttp 9136 9460 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:08,893 log 9136 5940 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:08,893 basehttp 9136 5940 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:09,018 log 9136 11428 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:09,018 basehttp 9136 11428 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:09,123 log 9136 3876 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:09,123 basehttp 9136 3876 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:09,253 log 9136 2060 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:09,254 basehttp 9136 2060 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:09,360 log 9136 26220 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:09,360 basehttp 9136 26220 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:09,487 log 9136 1972 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:09,488 basehttp 9136 1972 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:09,611 log 9136 7692 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:09,611 basehttp 9136 7692 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:09,736 log 9136 3704 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:09,737 basehttp 9136 3704 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:09,858 log 9136 9916 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:09,859 basehttp 9136 9916 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:09,965 log 9136 12728 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:09,965 basehttp 9136 12728 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:10,095 log 9136 3820 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:10,096 basehttp 9136 3820 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:10,220 log 9136 21704 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:10,220 basehttp 9136 21704 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:10,328 log 9136 9296 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:10,329 basehttp 9136 9296 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:10,450 log 9136 20472 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:10,451 basehttp 9136 20472 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:10,575 log 9136 7644 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:10,576 basehttp 9136 7644 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:10,702 log 9136 4944 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:10,702 basehttp 9136 4944 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:10,808 log 9136 20936 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:10,808 basehttp 9136 20936 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:10,934 log 9136 26392 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:10,935 basehttp 9136 26392 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:11,059 log 9136 15932 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:11,060 basehttp 9136 15932 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:11,188 log 9136 13976 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:11,189 basehttp 9136 13976 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:11,295 log 9136 10708 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:11,296 basehttp 9136 10708 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:11,401 log 9136 19496 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:11,401 basehttp 9136 19496 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:11,506 log 9136 4708 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:11,507 basehttp 9136 4708 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:11,624 log 9136 12264 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:11,624 basehttp 9136 12264 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:11,729 log 9136 8680 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:11,729 basehttp 9136 8680 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:11,833 log 9136 5216 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:11,833 basehttp 9136 5216 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:11,950 log 9136 18412 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:11,950 basehttp 9136 18412 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:12,075 log 9136 6408 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:12,075 basehttp 9136 6408 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:12,197 log 9136 10388 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:12,198 basehttp 9136 10388 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:12,323 log 9136 20564 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:12,324 basehttp 9136 20564 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:12,430 log 9136 16676 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:12,430 basehttp 9136 16676 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:12,535 log 9136 23164 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:12,535 basehttp 9136 23164 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:12,639 log 9136 19168 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:12,640 basehttp 9136 19168 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:12,760 log 9136 20708 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:12,761 basehttp 9136 20708 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:12,866 log 9136 12048 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:12,866 basehttp 9136 12048 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:12,991 log 9136 12436 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:12,992 basehttp 9136 12436 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:13,099 log 9136 1732 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:13,099 basehttp 9136 1732 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:13,223 log 9136 15076 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:13,224 basehttp 9136 15076 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:13,330 log 9136 20756 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:13,330 basehttp 9136 20756 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:13,458 log 9136 11076 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:13,458 basehttp 9136 11076 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:13,583 log 9136 7892 Not Found: /api/teltonika-gps/
WARNING 2025-07-06 23:10:13,584 basehttp 9136 7892 "POST /api/teltonika-gps/ HTTP/1.1" 404 4988
WARNING 2025-07-06 23:10:13,695 log 9136 9656 Not Found: /api/devices/999888777666555/gps-records/
WARNING 2025-07-06 23:10:13,696 basehttp 9136 9656 "GET /api/devices/999888777666555/gps-records/?limit=10 HTTP/1.1" 404 5062
WARNING 2025-07-06 23:10:13,700 log 9136 9752 Not Found: /api/devices/999888777666555/gps-records/
WARNING 2025-07-06 23:10:13,701 basehttp 9136 9752 "GET /api/devices/999888777666555/gps-records/ HTTP/1.1" 404 5053
WARNING 2025-07-06 23:10:13,705 log 9136 10600 Not Found: /api/latest-gps-records/
WARNING 2025-07-06 23:10:13,705 basehttp 9136 10600 "GET /api/latest-gps-records/?limit=100 HTTP/1.1" 404 5012
WARNING 2025-07-06 23:10:13,723 log 9136 8900 Not Found: /api/devices/999888777666555/gps-records/
WARNING 2025-07-06 23:10:13,724 basehttp 9136 8900 "GET /api/devices/999888777666555/gps-records/?limit=50 HTTP/1.1" 404 5062
INFO 2025-07-06 23:10:57,180 basehttp 9136 27376 "GET /api/health/ HTTP/1.1" 200 108
INFO 2025-07-06 23:11:02,060 basehttp 9136 27460 "GET /api/health/ HTTP/1.1" 200 108
WARNING 2025-07-06 23:11:02,108 log 9136 5076 Bad Request: /api/devices/
WARNING 2025-07-06 23:11:02,108 basehttp 9136 5076 "POST /api/devices/ HTTP/1.1" 400 50
INFO 2025-07-06 23:11:02,177 views 9136 26628 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:02,178 views 9136 26628 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:02,211 basehttp 9136 26628 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:02,315 views 9136 27628 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:02,315 views 9136 27628 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:02,342 basehttp 9136 27628 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:02,446 views 9136 26668 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:02,447 views 9136 26668 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:02,480 basehttp 9136 26668 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:02,597 views 9136 26716 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:02,597 views 9136 26716 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:02,622 basehttp 9136 26716 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:02,739 views 9136 6756 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:02,739 views 9136 6756 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:02,765 basehttp 9136 6756 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:02,879 views 9136 26764 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:02,880 views 9136 26764 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:02,906 basehttp 9136 26764 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:03,009 views 9136 26780 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:03,009 views 9136 26780 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:03,034 basehttp 9136 26780 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:03,137 views 9136 26936 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:03,138 views 9136 26936 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:03,169 basehttp 9136 26936 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:03,287 views 9136 25888 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:03,290 views 9136 25888 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:03,318 basehttp 9136 25888 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:03,442 views 9136 26688 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:03,443 views 9136 26688 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:03,471 basehttp 9136 26688 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:03,599 views 9136 7132 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:03,600 views 9136 7132 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:03,625 basehttp 9136 7132 "POST /api/gps/ HTTP/1.1" 200 99
INFO 2025-07-06 23:11:03,753 views 9136 15600 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:03,753 views 9136 15600 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:03,779 basehttp 9136 15600 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:03,893 views 9136 10040 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:03,893 views 9136 10040 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:03,925 basehttp 9136 10040 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:04,047 views 9136 592 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:04,047 views 9136 592 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:04,075 basehttp 9136 592 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:04,178 views 9136 18688 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:04,179 views 9136 18688 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:04,211 basehttp 9136 18688 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:04,316 views 9136 25292 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:04,317 views 9136 25292 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:04,346 basehttp 9136 25292 "POST /api/gps/ HTTP/1.1" 200 99
INFO 2025-07-06 23:11:04,468 views 9136 27032 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:04,468 views 9136 27032 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:04,496 basehttp 9136 27032 "POST /api/gps/ HTTP/1.1" 200 98
INFO 2025-07-06 23:11:04,602 views 9136 9180 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:04,602 views 9136 9180 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:04,636 basehttp 9136 9180 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:04,749 views 9136 11072 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:04,750 views 9136 11072 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:04,778 basehttp 9136 11072 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:04,883 views 9136 11388 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:04,884 views 9136 11388 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:04,916 basehttp 9136 11388 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:05,020 views 9136 26812 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:05,021 views 9136 26812 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:05,049 basehttp 9136 26812 "POST /api/gps/ HTTP/1.1" 200 99
INFO 2025-07-06 23:11:05,172 views 9136 27344 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:05,172 views 9136 27344 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:05,198 basehttp 9136 27344 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:05,302 views 9136 23568 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:05,303 views 9136 23568 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:05,332 basehttp 9136 23568 "POST /api/gps/ HTTP/1.1" 200 99
INFO 2025-07-06 23:11:05,453 views 9136 27332 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:05,453 views 9136 27332 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:05,481 basehttp 9136 27332 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:05,584 views 9136 27440 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:05,584 views 9136 27440 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:05,611 basehttp 9136 27440 "POST /api/gps/ HTTP/1.1" 200 99
INFO 2025-07-06 23:11:05,734 views 9136 27532 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:05,734 views 9136 27532 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:05,761 basehttp 9136 27532 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:05,865 views 9136 26844 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:05,866 views 9136 26844 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:05,895 basehttp 9136 26844 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:05,999 views 9136 17844 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:06,000 views 9136 17844 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:06,028 basehttp 9136 17844 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:06,154 views 9136 4732 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:06,155 views 9136 4732 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:06,183 basehttp 9136 4732 "POST /api/gps/ HTTP/1.1" 200 99
INFO 2025-07-06 23:11:06,308 views 9136 26424 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:06,309 views 9136 26424 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:06,335 basehttp 9136 26424 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:06,449 views 9136 26704 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:06,450 views 9136 26704 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:06,479 basehttp 9136 26704 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:06,583 views 9136 26640 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:06,585 views 9136 26640 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:06,618 basehttp 9136 26640 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:06,731 views 9136 16112 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:06,732 views 9136 16112 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:06,758 basehttp 9136 16112 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:06,863 views 9136 26792 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:06,864 views 9136 26792 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:06,896 basehttp 9136 26792 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:07,012 views 9136 26992 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:07,013 views 9136 26992 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:07,040 basehttp 9136 26992 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:07,146 views 9136 26924 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:07,146 views 9136 26924 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:07,176 basehttp 9136 26924 "POST /api/gps/ HTTP/1.1" 200 99
INFO 2025-07-06 23:11:07,280 views 9136 26684 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:07,281 views 9136 26684 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:07,317 basehttp 9136 26684 "POST /api/gps/ HTTP/1.1" 200 99
INFO 2025-07-06 23:11:07,420 views 9136 8420 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:07,421 views 9136 8420 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:07,451 basehttp 9136 8420 "POST /api/gps/ HTTP/1.1" 200 99
INFO 2025-07-06 23:11:07,576 views 9136 6280 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:07,577 views 9136 6280 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:07,606 basehttp 9136 6280 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:07,730 views 9136 21408 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:07,730 views 9136 21408 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:07,757 basehttp 9136 21408 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:07,860 views 9136 27084 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:07,861 views 9136 27084 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:08,008 basehttp 9136 27084 "POST /api/gps/ HTTP/1.1" 200 99
INFO 2025-07-06 23:11:08,133 views 9136 24780 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:08,133 views 9136 24780 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:08,160 basehttp 9136 24780 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:08,289 views 9136 7768 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:08,289 views 9136 7768 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:08,432 basehttp 9136 7768 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:08,554 views 9136 9948 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:08,555 views 9136 9948 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:08,580 basehttp 9136 9948 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:08,694 views 9136 22852 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:08,696 views 9136 22852 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:08,723 basehttp 9136 22852 "POST /api/gps/ HTTP/1.1" 200 99
INFO 2025-07-06 23:11:08,850 views 9136 26280 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:08,851 views 9136 26280 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:08,877 basehttp 9136 26280 "POST /api/gps/ HTTP/1.1" 200 99
INFO 2025-07-06 23:11:08,982 views 9136 8256 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:08,982 views 9136 8256 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:09,013 basehttp 9136 8256 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:09,130 views 9136 18028 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:09,131 views 9136 18028 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:09,161 basehttp 9136 18028 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:09,288 views 9136 26892 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:09,289 views 9136 26892 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:09,318 basehttp 9136 26892 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:11:09,444 views 9136 8408 Received GPS data: 1 bytes
WARNING 2025-07-06 23:11:09,445 views 9136 8408 Invalid GPS record data: {'imei': [ErrorDetail(string='This field is required.', code='required')], 'timestamp': [ErrorDetail(string='This field is required.', code='required')], 'gps_data': [ErrorDetail(string='Expected a dictionary of items but got type "list".', code='not_a_dict')]}
INFO 2025-07-06 23:11:09,475 basehttp 9136 8408 "POST /api/gps/ HTTP/1.1" 200 99
INFO 2025-07-06 23:11:09,632 basehttp 9136 2096 "GET /api/devices/999888777666555/records/?limit=10 HTTP/1.1" 200 52
INFO 2025-07-06 23:11:09,677 basehttp 9136 27268 "GET /api/devices/999888777666555/records/ HTTP/1.1" 200 52
INFO 2025-07-06 23:11:09,728 basehttp 9136 27388 "GET /api/records/latest/?limit=100 HTTP/1.1" 200 727
INFO 2025-07-06 23:11:09,770 basehttp 9136 27420 "GET /api/devices/999888777666555/records/?limit=50 HTTP/1.1" 200 52
INFO 2025-07-06 23:11:13,091 basehttp 9136 27376 - Broken pipe from ('127.0.0.1', 51771)
ERROR 2025-07-06 23:11:30,249 log 9136 2096 Internal Server Error: /admin/gps_data/gpsrecord/
Traceback (most recent call last):
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\options.py", line 683, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'coordinates'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\utils.py", line 290, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\utils.py", line 330, in _get_non_gfk_field
    field = opts.get_field(name)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\options.py", line 685, in get_field
    raise FieldDoesNotExist(
        "%s has no field named '%s'" % (self.object_name, field_name)
    )
django.core.exceptions.FieldDoesNotExist: GPSRecord has no field named 'coordinates'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\library.py", line 359, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 354, in result_list
    "results": list(results(cl)),
               ~~~~^^^^^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 330, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 321, in __init__
    super().__init__(*items)
    ~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 219, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\utils.py", line 299, in lookup_field
    value = attr(obj)
  File "D:\GitHub\teltonika\django\gps_data\admin.py", line 93, in coordinates
    return format_html(
        '<a href="{}" target="_blank">{:.6f}, {:.6f}</a>',
        maps_url, lat, lon
    )
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\html.py", line 145, in format_html
    return mark_safe(format_string.format(*args_safe, **kwargs_safe))
                     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unknown format code 'f' for object of type 'SafeString'
ERROR 2025-07-06 23:11:30,253 basehttp 9136 2096 "GET /admin/gps_data/gpsrecord/ HTTP/1.1" 500 358411
ERROR 2025-07-06 23:11:31,783 log 9136 2096 Internal Server Error: /admin/gps_data/gpsrecord/
Traceback (most recent call last):
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\options.py", line 683, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'coordinates'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\utils.py", line 290, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\utils.py", line 330, in _get_non_gfk_field
    field = opts.get_field(name)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\options.py", line 685, in get_field
    raise FieldDoesNotExist(
        "%s has no field named '%s'" % (self.object_name, field_name)
    )
django.core.exceptions.FieldDoesNotExist: GPSRecord has no field named 'coordinates'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\library.py", line 359, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 354, in result_list
    "results": list(results(cl)),
               ~~~~^^^^^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 330, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 321, in __init__
    super().__init__(*items)
    ~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 219, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\utils.py", line 299, in lookup_field
    value = attr(obj)
  File "D:\GitHub\teltonika\django\gps_data\admin.py", line 93, in coordinates
    return format_html(
        '<a href="{}" target="_blank">{:.6f}, {:.6f}</a>',
        maps_url, lat, lon
    )
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\html.py", line 145, in format_html
    return mark_safe(format_string.format(*args_safe, **kwargs_safe))
                     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unknown format code 'f' for object of type 'SafeString'
ERROR 2025-07-06 23:11:31,785 basehttp 9136 2096 "GET /admin/gps_data/gpsrecord/ HTTP/1.1" 500 358411
ERROR 2025-07-06 23:11:33,072 log 9136 2096 Internal Server Error: /admin/gps_data/gpsrecord/
Traceback (most recent call last):
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\options.py", line 683, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'coordinates'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\utils.py", line 290, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\utils.py", line 330, in _get_non_gfk_field
    field = opts.get_field(name)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\options.py", line 685, in get_field
    raise FieldDoesNotExist(
        "%s has no field named '%s'" % (self.object_name, field_name)
    )
django.core.exceptions.FieldDoesNotExist: GPSRecord has no field named 'coordinates'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\library.py", line 359, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 354, in result_list
    "results": list(results(cl)),
               ~~~~^^^^^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 330, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 321, in __init__
    super().__init__(*items)
    ~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 219, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\utils.py", line 299, in lookup_field
    value = attr(obj)
  File "D:\GitHub\teltonika\django\gps_data\admin.py", line 93, in coordinates
    return format_html(
        '<a href="{}" target="_blank">{:.6f}, {:.6f}</a>',
        maps_url, lat, lon
    )
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\html.py", line 145, in format_html
    return mark_safe(format_string.format(*args_safe, **kwargs_safe))
                     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unknown format code 'f' for object of type 'SafeString'
ERROR 2025-07-06 23:11:33,075 basehttp 9136 2096 "GET /admin/gps_data/gpsrecord/ HTTP/1.1" 500 358411
INFO 2025-07-06 23:11:41,715 autoreload 14808 22920 Watching for file changes with StatReloader
ERROR 2025-07-06 23:11:46,441 log 14808 27500 Internal Server Error: /admin/gps_data/gpsrecord/
Traceback (most recent call last):
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\options.py", line 683, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'coordinates'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\utils.py", line 290, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\utils.py", line 330, in _get_non_gfk_field
    field = opts.get_field(name)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\options.py", line 685, in get_field
    raise FieldDoesNotExist(
        "%s has no field named '%s'" % (self.object_name, field_name)
    )
django.core.exceptions.FieldDoesNotExist: GPSRecord has no field named 'coordinates'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\library.py", line 359, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 354, in result_list
    "results": list(results(cl)),
               ~~~~^^^^^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 330, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 321, in __init__
    super().__init__(*items)
    ~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 219, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\utils.py", line 299, in lookup_field
    value = attr(obj)
  File "D:\GitHub\teltonika\django\gps_data\admin.py", line 93, in coordinates
    return format_html(
        '<a href="{}" target="_blank">{:.6f}, {:.6f}</a>',
        maps_url, lat, lon
    )
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\html.py", line 145, in format_html
    return mark_safe(format_string.format(*args_safe, **kwargs_safe))
                     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unknown format code 'f' for object of type 'SafeString'
ERROR 2025-07-06 23:11:46,445 basehttp 14808 27500 "GET /admin/gps_data/gpsrecord/ HTTP/1.1" 500 358411
ERROR 2025-07-06 23:11:46,936 log 14808 27500 Internal Server Error: /admin/gps_data/gpsrecord/
Traceback (most recent call last):
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\options.py", line 683, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'coordinates'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\utils.py", line 290, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\utils.py", line 330, in _get_non_gfk_field
    field = opts.get_field(name)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\options.py", line 685, in get_field
    raise FieldDoesNotExist(
        "%s has no field named '%s'" % (self.object_name, field_name)
    )
django.core.exceptions.FieldDoesNotExist: GPSRecord has no field named 'coordinates'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\library.py", line 359, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 354, in result_list
    "results": list(results(cl)),
               ~~~~^^^^^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 330, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 321, in __init__
    super().__init__(*items)
    ~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 219, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\admin\utils.py", line 299, in lookup_field
    value = attr(obj)
  File "D:\GitHub\teltonika\django\gps_data\admin.py", line 93, in coordinates
    return format_html(
        '<a href="{}" target="_blank">{:.6f}, {:.6f}</a>',
        maps_url, lat, lon
    )
  File "C:\Users\abdel\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\html.py", line 145, in format_html
    return mark_safe(format_string.format(*args_safe, **kwargs_safe))
                     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unknown format code 'f' for object of type 'SafeString'
ERROR 2025-07-06 23:11:46,938 basehttp 14808 27500 "GET /admin/gps_data/gpsrecord/ HTTP/1.1" 500 358411
INFO 2025-07-06 23:12:13,008 autoreload 14808 22920 D:\GitHub\teltonika\django\gps_data\admin.py changed, reloading.
INFO 2025-07-06 23:12:13,537 autoreload 26472 13276 Watching for file changes with StatReloader
INFO 2025-07-06 23:12:31,290 basehttp 26472 6756 "GET /admin/gps_data/gpsrecord/ HTTP/1.1" 200 26280
INFO 2025-07-06 23:12:31,355 basehttp 26472 6756 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:12:31,449 basehttp 26472 6756 "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
INFO 2025-07-06 23:12:34,510 basehttp 26472 6756 "GET /admin/gps_data/apilog/ HTTP/1.1" 200 42534
INFO 2025-07-06 23:12:34,574 basehttp 26472 6756 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:12:38,532 basehttp 26472 6756 "POST /admin/gps_data/apilog/ HTTP/1.1" 200 17949
INFO 2025-07-06 23:12:38,583 basehttp 26472 6756 "GET /static/admin/js/cancel.js HTTP/1.1" 200 884
INFO 2025-07-06 23:12:40,502 basehttp 26472 6756 "GET /admin/gps_data/gpsrecord/ HTTP/1.1" 200 26280
INFO 2025-07-06 23:12:40,563 basehttp 26472 6756 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:12:41,769 basehttp 26472 6756 "GET /admin/gps_data/gpsrecord/9/change/ HTTP/1.1" 200 40937
INFO 2025-07-06 23:12:41,834 basehttp 26472 6756 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:12:44,527 basehttp 26472 6756 "GET /admin/gps_data/gpsrecord/ HTTP/1.1" 200 26280
INFO 2025-07-06 23:12:47,535 basehttp 26472 6756 "POST /admin/gps_data/gpsrecord/ HTTP/1.1" 200 12470
INFO 2025-07-06 23:12:48,465 basehttp 26472 6756 "POST /admin/gps_data/gpsrecord/ HTTP/1.1" 302 0
INFO 2025-07-06 23:12:48,521 basehttp 26472 6756 "GET /admin/gps_data/gpsrecord/ HTTP/1.1" 200 13236
INFO 2025-07-06 23:12:48,578 basehttp 26472 6756 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:12:49,669 basehttp 26472 6756 "GET /admin/gps_data/device/ HTTP/1.1" 200 14436
INFO 2025-07-06 23:12:49,722 basehttp 26472 6756 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:12:54,449 basehttp 26472 6756 "POST /admin/gps_data/device/ HTTP/1.1" 200 9950
INFO 2025-07-06 23:12:55,151 basehttp 26472 6756 "POST /admin/gps_data/device/ HTTP/1.1" 302 0
INFO 2025-07-06 23:12:55,198 basehttp 26472 6756 "GET /admin/gps_data/device/ HTTP/1.1" 200 11468
INFO 2025-07-06 23:12:55,250 basehttp 26472 6756 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:12:56,222 basehttp 26472 6756 "GET /admin/gps_data/devicestatus/ HTTP/1.1" 200 12517
INFO 2025-07-06 23:12:56,280 basehttp 26472 6756 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:12:57,768 basehttp 26472 6756 "GET /admin/gps_data/apilog/ HTTP/1.1" 200 42534
INFO 2025-07-06 23:12:57,929 basehttp 26472 6756 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:13:31,704 autoreload 26472 13276 D:\GitHub\teltonika\django\gps_data\admin.py changed, reloading.
INFO 2025-07-06 23:13:32,189 autoreload 20224 12560 Watching for file changes with StatReloader
WARNING 2025-07-06 23:14:06,414 log 20224 26524 Not Found: /admin/gps_data/apilog/
WARNING 2025-07-06 23:14:06,414 basehttp 20224 26524 "GET /admin/gps_data/apilog/ HTTP/1.1" 404 6233
WARNING 2025-07-06 23:14:07,560 log 20224 26524 Not Found: /admin/gps_data/apilog/
WARNING 2025-07-06 23:14:07,560 basehttp 20224 26524 "GET /admin/gps_data/apilog/ HTTP/1.1" 404 6233
INFO 2025-07-06 23:14:10,167 basehttp 20224 26524 "GET /admin/ HTTP/1.1" 200 12125
INFO 2025-07-06 23:14:10,190 basehttp 20224 26524 "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 304 0
INFO 2025-07-06 23:14:12,034 basehttp 20224 26524 "GET /admin/gps_data/gpsrecord/ HTTP/1.1" 200 12434
INFO 2025-07-06 23:14:12,081 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:14:13,748 basehttp 20224 26524 "GET /admin/gps_data/device/ HTTP/1.1" 200 11000
INFO 2025-07-06 23:14:13,809 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:14:14,971 basehttp 20224 26524 "GET /admin/gps_data/devicestatus/ HTTP/1.1" 200 12186
INFO 2025-07-06 23:14:15,031 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
WARNING 2025-07-06 23:14:45,630 log 20224 12632 Not Found: /health/
WARNING 2025-07-06 23:14:45,631 basehttp 20224 12632 "GET /health/ HTTP/1.1" 404 2350
INFO 2025-07-06 23:15:26,651 basehttp 20224 12632 - Broken pipe from ('127.0.0.1', 52056)
WARNING 2025-07-06 23:15:55,649 log 20224 22852 Not Found: /gps/
WARNING 2025-07-06 23:15:55,650 basehttp 20224 22852 "POST /gps/ HTTP/1.1" 404 2342
WARNING 2025-07-06 23:15:57,837 log 20224 22852 Not Found: /gps/
WARNING 2025-07-06 23:15:57,837 basehttp 20224 22852 "POST /gps/ HTTP/1.1" 404 2342
WARNING 2025-07-06 23:16:02,562 log 20224 22852 Not Found: /gps/
WARNING 2025-07-06 23:16:02,562 basehttp 20224 22852 "POST /gps/ HTTP/1.1" 404 2342
WARNING 2025-07-06 23:16:03,183 log 20224 22852 Not Found: /gps/
WARNING 2025-07-06 23:16:03,183 basehttp 20224 22852 "POST /gps/ HTTP/1.1" 404 2342
WARNING 2025-07-06 23:16:03,785 log 20224 22852 Not Found: /gps/
WARNING 2025-07-06 23:16:03,786 basehttp 20224 22852 "POST /gps/ HTTP/1.1" 404 2342
WARNING 2025-07-06 23:16:04,441 log 20224 22852 Not Found: /gps/
WARNING 2025-07-06 23:16:04,442 basehttp 20224 22852 "POST /gps/ HTTP/1.1" 404 2342
WARNING 2025-07-06 23:16:09,625 log 20224 22852 Not Found: /gps/
WARNING 2025-07-06 23:16:09,627 basehttp 20224 22852 "POST /gps/ HTTP/1.1" 404 2342
INFO 2025-07-06 23:16:23,905 basehttp 20224 26524 "GET /admin/gps_data/devicestatus/ HTTP/1.1" 200 12186
INFO 2025-07-06 23:16:23,961 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:16:24,915 basehttp 20224 26524 "GET /admin/gps_data/device/ HTTP/1.1" 200 11000
INFO 2025-07-06 23:16:24,975 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:16:25,496 basehttp 20224 26524 "GET /admin/gps_data/gpsrecord/ HTTP/1.1" 200 12434
INFO 2025-07-06 23:16:25,549 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:16:26,052 basehttp 20224 26524 "GET /admin/gps_data/device/ HTTP/1.1" 200 11000
INFO 2025-07-06 23:16:26,100 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:16:26,477 basehttp 20224 26524 "GET /admin/gps_data/devicestatus/ HTTP/1.1" 200 12186
INFO 2025-07-06 23:16:26,522 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:17:23,213 basehttp 20224 26524 "GET /admin/gps_data/devicestatus/ HTTP/1.1" 200 12186
INFO 2025-07-06 23:17:23,383 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:17:24,665 basehttp 20224 26524 "GET /admin/gps_data/device/ HTTP/1.1" 200 11000
INFO 2025-07-06 23:17:24,726 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:17:25,307 basehttp 20224 26524 "GET /admin/gps_data/gpsrecord/ HTTP/1.1" 200 12434
INFO 2025-07-06 23:17:25,373 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:17:25,937 basehttp 20224 26524 "GET /admin/gps_data/device/ HTTP/1.1" 200 11000
INFO 2025-07-06 23:17:26,105 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:18:58,206 basehttp 20224 22852 - Broken pipe from ('127.0.0.1', 52105)
INFO 2025-07-06 23:19:26,011 basehttp 20224 27004 "GET /api/health/ HTTP/1.1" 200 108
INFO 2025-07-06 23:19:53,815 views 20224 27004 Received GPS data: 50 bytes
INFO 2025-07-06 23:19:53,925 basehttp 20224 27004 "POST /api/gps/ HTTP/1.1" 200 102
INFO 2025-07-06 23:19:58,060 views 20224 27004 Received GPS data: 50 bytes
INFO 2025-07-06 23:19:58,163 basehttp 20224 27004 "POST /api/gps/ HTTP/1.1" 200 102
INFO 2025-07-06 23:20:02,766 views 20224 27004 Received GPS data: 50 bytes
INFO 2025-07-06 23:20:02,875 basehttp 20224 27004 "POST /api/gps/ HTTP/1.1" 200 102
INFO 2025-07-06 23:20:03,361 views 20224 27004 Received GPS data: 50 bytes
INFO 2025-07-06 23:20:03,474 basehttp 20224 27004 "POST /api/gps/ HTTP/1.1" 200 102
INFO 2025-07-06 23:20:03,955 views 20224 27004 Received GPS data: 50 bytes
INFO 2025-07-06 23:20:04,068 basehttp 20224 27004 "POST /api/gps/ HTTP/1.1" 200 102
INFO 2025-07-06 23:20:04,279 basehttp 20224 26524 "GET /admin/gps_data/device/ HTTP/1.1" 200 14778
INFO 2025-07-06 23:20:04,322 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:20:04,553 views 20224 27004 Received GPS data: 50 bytes
INFO 2025-07-06 23:20:04,763 basehttp 20224 27004 "POST /api/gps/ HTTP/1.1" 200 102
INFO 2025-07-06 23:20:08,862 basehttp 20224 26524 "GET /admin/gps_data/device/ HTTP/1.1" 200 14778
INFO 2025-07-06 23:20:08,913 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:20:09,659 basehttp 20224 26524 "GET /admin/gps_data/gpsrecord/ HTTP/1.1" 200 93407
INFO 2025-07-06 23:20:09,813 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:20:09,823 views 20224 27004 Received GPS data: 10 bytes
INFO 2025-07-06 23:20:09,876 basehttp 20224 27004 "POST /api/gps/ HTTP/1.1" 200 102
INFO 2025-07-06 23:20:16,749 basehttp 20224 26524 "GET /admin/gps_data/gpsrecord/314/change/ HTTP/1.1" 200 40684
INFO 2025-07-06 23:20:16,801 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:20:25,375 basehttp 20224 26524 "GET /admin/gps_data/devicestatus/ HTTP/1.1" 200 16014
INFO 2025-07-06 23:20:25,421 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:20:28,017 basehttp 20224 26524 "GET /admin/gps_data/devicestatus/4/change/ HTTP/1.1" 200 15976
INFO 2025-07-06 23:20:28,171 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:20:32,439 basehttp 20224 26524 "GET /admin/gps_data/devicestatus/ HTTP/1.1" 200 16014
INFO 2025-07-06 23:20:33,952 basehttp 20224 26524 "GET /admin/gps_data/devicestatus/4/change/ HTTP/1.1" 200 15976
INFO 2025-07-06 23:20:33,999 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:20:37,336 basehttp 20224 26524 "GET /admin/gps_data/devicestatus/ HTTP/1.1" 200 16014
INFO 2025-07-06 23:20:39,541 basehttp 20224 26524 "POST /admin/gps_data/devicestatus/ HTTP/1.1" 200 9699
INFO 2025-07-06 23:20:40,412 basehttp 20224 26524 "POST /admin/gps_data/devicestatus/ HTTP/1.1" 302 0
INFO 2025-07-06 23:20:40,450 basehttp 20224 26524 "GET /admin/gps_data/devicestatus/ HTTP/1.1" 200 12330
INFO 2025-07-06 23:20:40,498 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:20:41,230 basehttp 20224 26524 "GET /admin/gps_data/device/ HTTP/1.1" 200 14781
INFO 2025-07-06 23:20:41,278 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:20:44,674 basehttp 20224 26524 "POST /admin/gps_data/device/ HTTP/1.1" 200 55800
INFO 2025-07-06 23:20:48,388 basehttp 20224 26524 "POST /admin/gps_data/device/ HTTP/1.1" 302 0
INFO 2025-07-06 23:20:48,421 basehttp 20224 26524 "GET /admin/gps_data/device/ HTTP/1.1" 200 11137
INFO 2025-07-06 23:20:48,468 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:20:49,859 basehttp 20224 26524 "GET /admin/gps_data/gpsrecord/ HTTP/1.1" 200 12434
INFO 2025-07-06 23:20:49,906 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:20:50,305 basehttp 20224 26524 "GET /admin/gps_data/device/ HTTP/1.1" 200 11000
INFO 2025-07-06 23:20:50,351 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:20:51,431 basehttp 20224 26524 "GET /admin/gps_data/devicestatus/ HTTP/1.1" 200 12186
INFO 2025-07-06 23:20:51,487 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:20:54,282 views 20224 27004 Received GPS data: 1 bytes
INFO 2025-07-06 23:20:54,317 basehttp 20224 27004 "POST /api/gps/ HTTP/1.1" 200 101
INFO 2025-07-06 23:20:57,926 views 20224 27004 Received GPS data: 50 bytes
INFO 2025-07-06 23:20:58,033 basehttp 20224 27004 "POST /api/gps/ HTTP/1.1" 200 102
INFO 2025-07-06 23:20:59,172 views 20224 27004 Received GPS data: 50 bytes
INFO 2025-07-06 23:20:59,292 basehttp 20224 27004 "POST /api/gps/ HTTP/1.1" 200 102
INFO 2025-07-06 23:21:03,913 views 20224 27004 Received GPS data: 50 bytes
INFO 2025-07-06 23:21:04,025 basehttp 20224 27004 "POST /api/gps/ HTTP/1.1" 200 102
INFO 2025-07-06 23:21:04,537 views 20224 27004 Received GPS data: 50 bytes
INFO 2025-07-06 23:21:04,768 basehttp 20224 27004 "POST /api/gps/ HTTP/1.1" 200 102
INFO 2025-07-06 23:21:05,153 views 20224 27004 Received GPS data: 50 bytes
INFO 2025-07-06 23:21:05,270 basehttp 20224 27004 "POST /api/gps/ HTTP/1.1" 200 102
INFO 2025-07-06 23:21:05,764 views 20224 27004 Received GPS data: 50 bytes
INFO 2025-07-06 23:21:05,867 basehttp 20224 27004 "POST /api/gps/ HTTP/1.1" 200 101
INFO 2025-07-06 23:21:10,935 views 20224 27004 Received GPS data: 9 bytes
INFO 2025-07-06 23:21:10,989 basehttp 20224 27004 "POST /api/gps/ HTTP/1.1" 200 100
INFO 2025-07-06 23:21:14,509 basehttp 20224 26524 "GET /admin/gps_data/gpsrecord/ HTTP/1.1" 200 93471
INFO 2025-07-06 23:21:14,662 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:21:20,864 basehttp 20224 26524 "GET /admin/gps_data/gpsrecord/634/change/ HTTP/1.1" 200 40686
INFO 2025-07-06 23:21:20,918 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:21:25,492 basehttp 20224 26524 "GET /admin/gps_data/devicestatus/ HTTP/1.1" 200 16014
INFO 2025-07-06 23:21:25,551 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:21:26,689 basehttp 20224 26524 "GET /admin/gps_data/gpsrecord/ HTTP/1.1" 200 93471
INFO 2025-07-06 23:21:26,860 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:21:28,567 basehttp 20224 26524 "GET /admin/gps_data/gpsrecord/622/change/ HTTP/1.1" 200 40677
INFO 2025-07-06 23:21:28,636 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:21:37,905 basehttp 20224 26524 "GET /admin/gps_data/devicestatus/ HTTP/1.1" 200 16014
INFO 2025-07-06 23:21:37,975 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:21:39,856 basehttp 20224 26524 "GET /admin/gps_data/device/ HTTP/1.1" 200 14778
INFO 2025-07-06 23:21:39,922 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:21:41,215 basehttp 20224 26524 "GET /admin/gps_data/devicestatus/ HTTP/1.1" 200 16014
INFO 2025-07-06 23:21:41,263 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:21:42,392 basehttp 20224 26524 "GET /admin/gps_data/devicestatus/6/change/ HTTP/1.1" 200 15976
INFO 2025-07-06 23:21:42,449 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:21:46,446 basehttp 20224 26524 "GET /admin/gps_data/devicestatus/ HTTP/1.1" 200 16014
INFO 2025-07-06 23:21:46,496 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:21:47,615 basehttp 20224 26524 "GET /admin/gps_data/devicestatus/6/change/ HTTP/1.1" 200 15976
INFO 2025-07-06 23:21:47,792 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:21:50,360 basehttp 20224 26524 "GET /admin/gps_data/devicestatus/ HTTP/1.1" 200 16014
INFO 2025-07-06 23:21:50,422 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:21:51,533 basehttp 20224 26524 "GET /admin/gps_data/devicestatus/5/change/ HTTP/1.1" 200 15977
INFO 2025-07-06 23:21:51,592 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:21:54,527 basehttp 20224 26524 "GET /admin/gps_data/devicestatus/ HTTP/1.1" 200 16014
INFO 2025-07-06 23:21:54,579 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:21:56,438 basehttp 20224 26524 "GET /admin/gps_data/device/ HTTP/1.1" 200 14778
INFO 2025-07-06 23:21:56,489 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-07-06 23:21:58,708 basehttp 20224 26524 "POST /admin/gps_data/device/ HTTP/1.1" 200 56239
INFO 2025-07-06 23:22:02,168 basehttp 20224 26524 "POST /admin/gps_data/device/ HTTP/1.1" 302 0
INFO 2025-07-06 23:22:02,257 basehttp 20224 26524 "GET /admin/gps_data/device/ HTTP/1.1" 200 11137
INFO 2025-07-06 23:22:02,313 basehttp 20224 26524 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
